import {
  air,
  barLouge,
  checkout,
  spa,
  parking,
  playground,
  wifi,
  energey110,
  energey220,
  balcony,
  library,
  businessCenter,
  heliport,
  pier,
  restaurant,
  fireside,
  gameRoom,
  conventionRoom,
  solarium,
  meetingRoom,
  soccer,
  golf,
  recreation,
  nauticalSports,
  fitnessCenter,
  pool,
  heatedPool,
  chilndresPool,
  indoorPool,
  cooper,
  shuttlecock,
  squash,
  tennis,
  multisport,
  medicAssistence,
  soiree24,
  medicalService,
  deficientAccess,
  wheelchair,
  academy,
  motorboat,
  hairdresser,
  multilingualStaff,
  transfer,
  petAccess,
  coffeeShop,
  baggage,
  rentalAgency,
  convenienceStore,
  valetParking,
  drySauna,
  steamSauna,
  laundry,
  dryLaundry,
  flatiron,
  roomService,
  roomService24,
  notebookStand,
  kitchen,
  vault,
  smokeDetector,
  power,
} from '@/assets/b2b/amenities/amenities-icons';

export interface IAmenity {
  amenity_id: number;
  name: string;
  visual_resource: string;
  description: string;
  imagePath?: string;
}

const amenities: IAmenity[] = [
  {
    amenity_id: 2,
    name: 'parking',
    visual_resource: 'parking',
    description: 'Estacionamento',
    imagePath: parking,
  },
  {
    amenity_id: 4,
    name: 'playground',
    visual_resource: 'playground',
    description: 'Recreação Infantil - Playground',
    imagePath: playground,
  },
  {
    amenity_id: 6,
    name: 'wifi',
    visual_resource: 'wifi',
    description: 'Wifi - internet sem fio',
    imagePath: wifi,
  },
  {
    amenity_id: 8,
    name: 'energey_110',
    visual_resource: 'energey_110',
    description: '110/120 V AC',
    imagePath: energey110,
  },
  {
    amenity_id: 10,
    name: 'energey_220',
    visual_resource: 'energey_220',
    description: '220/240 V AC',
    imagePath: energey220,
  },
  {
    amenity_id: 12,
    name: 'balcony',
    visual_resource: 'balcony',
    description: 'Apartamento com sacada',
    imagePath: balcony,
  },
  {
    amenity_id: 18,
    name: 'library',
    visual_resource: 'library',
    description: 'Biblioteca',
    imagePath: library,
  },
  {
    amenity_id: 20,
    name: 'bicycle_rack',
    visual_resource: 'bicycle_rack',
    description: 'Bicicletário',
  },
  {
    amenity_id: 22,
    name: 'business_center',
    visual_resource: 'business_center',
    description: 'Business center c/ wifi',
    imagePath: businessCenter,
  },
  {
    amenity_id: 28,
    name: 'heliport',
    visual_resource: 'heliport',
    description: 'Heliponto',
    imagePath: heliport,
  },
  {
    amenity_id: 32,
    name: 'pier',
    visual_resource: 'pier',
    description: 'Pier para embarcação',
    imagePath: pier,
  },
  {
    amenity_id: 34,
    name: 'restaurant',
    visual_resource: 'restaurant',
    description: 'Restaurante',
    imagePath: restaurant,
  },
  {
    amenity_id: 36,
    name: 'fireside',
    visual_resource: 'fireside',
    description: 'Sala de estar com lareira',
    imagePath: fireside,
  },
  {
    amenity_id: 38,
    name: 'game_room',
    visual_resource: 'game_room',
    description: 'Sala de jogos',
    imagePath: gameRoom,
  },
  {
    amenity_id: 40,
    name: 'massage_room',
    visual_resource: 'massage_room',
    description: 'Sala de massagem',
    imagePath: spa,
  },
  {
    amenity_id: 44,
    name: 'convention_room',
    visual_resource: 'convention_room',
    description: 'Salas de convenção',
    imagePath: conventionRoom,
  },
  {
    amenity_id: 46,
    name: 'meeting_room',
    visual_resource: 'meeting_room',
    description: 'Salas de reunião',
    imagePath: meetingRoom,
  },
  {
    amenity_id: 48,
    name: 'solarium',
    visual_resource: 'solarium',
    description: 'Solarium',
    imagePath: solarium,
  },
  {
    amenity_id: 94,
    name: 'soccer',
    visual_resource: 'soccer',
    description: 'Campo de futebol',
    imagePath: soccer,
  },
  {
    amenity_id: 96,
    name: 'golf',
    visual_resource: 'golf',
    description: 'Campo de golfe',
    imagePath: golf,
  },
  {
    amenity_id: 98,
    name: 'recreation',
    visual_resource: 'recreation',
    description: 'Equipe de lazer e recreação',
    imagePath: recreation,
  },
  {
    amenity_id: 100,
    name: 'nautical_sports',
    visual_resource: 'nautical_sports',
    description: 'Esportes náuticos',
    imagePath: nauticalSports,
  },
  {
    amenity_id: 102,
    name: 'fitness_center',
    visual_resource: 'fitness_center',
    description: 'Fitness center',
    imagePath: fitnessCenter,
  },
  {
    amenity_id: 104,
    name: 'pool',
    visual_resource: 'pool',
    description: 'Piscina',
    imagePath: pool,
  },
  {
    amenity_id: 106,
    name: 'external_pool',
    visual_resource: 'pool',
    description: 'Piscina externa',
    imagePath: pool,
  },
  {
    amenity_id: 108,
    name: 'adult_pool',
    visual_resource: 'pool',
    description: 'Piscina para adultos',
    imagePath: pool,
  },
  {
    amenity_id: 110,
    name: 'heated_pool',
    visual_resource: 'heated_pool',
    description: 'Piscina aquecida',
    imagePath: heatedPool,
  },
  {
    amenity_id: 114,
    name: 'chilndres_pool',
    visual_resource: 'chilndres_pool',
    description: 'Piscina infantil',
    imagePath: chilndresPool,
  },
  {
    amenity_id: 112,
    name: 'indoor_pool',
    visual_resource: 'indoor_pool',
    description: 'Piscina coberta',
    imagePath: indoorPool,
  },
  {
    amenity_id: 116,
    name: 'internal_pool',
    visual_resource: 'indoor_pool',
    description: 'Piscina interna',
    imagePath: indoorPool,
  },
  {
    amenity_id: 118,
    name: 'cooper',
    visual_resource: 'cooper',
    description: 'Pista cooper',
    imagePath: cooper,
  },
  {
    amenity_id: 120,
    name: 'sport_playground',
    visual_resource: 'playground',
    description: 'Playground',
    imagePath: playground,
  },
  {
    amenity_id: 122,
    name: 'shuttlecock',
    visual_resource: 'shuttlecock',
    description: 'Quadra de peteca',
    imagePath: shuttlecock,
  },
  {
    amenity_id: 124,
    name: 'squash',
    visual_resource: 'squash',
    description: 'Quadra de squash',
    imagePath: squash,
  },
  {
    amenity_id: 126,
    name: 'tennis',
    visual_resource: 'tennis',
    description: 'Quadra de tênis',
    imagePath: tennis,
  },
  {
    amenity_id: 128,
    name: 'multisport',
    visual_resource: 'multisport',
    description: 'Quadra poliesportiva',
    imagePath: multisport,
  },
  {
    amenity_id: 130,
    name: 'medic_assistence',
    visual_resource: 'medic_assistence',
    description: 'Assistência médica no hotel',
    imagePath: medicAssistence,
  },
  {
    amenity_id: 138,
    name: 'soiree_24',
    visual_resource: 'soiree_24',
    description: 'Recepção 24 horas',
    imagePath: soiree24,
  },
  {
    amenity_id: 140,
    name: 'medical_service',
    visual_resource: 'medical_service',
    description: 'Serviço médico',
    imagePath: medicalService,
  },
  {
    amenity_id: 142,
    name: 'deficient_access',
    visual_resource: 'deficient_access',
    description: 'Acesso para deficiente físico',
    imagePath: deficientAccess,
  },
  {
    amenity_id: 144,
    name: 'wheelchair',
    visual_resource: 'wheelchair',
    description: 'Cadeira de rodas',
    imagePath: wheelchair,
  },
  {
    amenity_id: 146,
    name: 'academy',
    visual_resource: 'academy',
    description: 'Academia de ginástica',
    imagePath: academy,
  },
  {
    amenity_id: 148,
    name: 'motorboat',
    visual_resource: 'motorboat',
    description: 'Aluguel de lancha/veleiro',
    imagePath: motorboat,
  },
  {
    amenity_id: 150,
    name: 'hairdresser',
    visual_resource: 'hairdresser',
    description: 'Cabeleireiro',
    imagePath: hairdresser,
  },
  {
    amenity_id: 152,
    name: 'multilingual_staff',
    visual_resource: 'multilingual_staff',
    description: 'Equipe multilíngue',
    imagePath: multilingualStaff,
  },
  {
    amenity_id: 154,
    name: 'transfer',
    visual_resource: 'transfer',
    description: 'Serviço de transfer',
    imagePath: transfer,
  },
  {
    amenity_id: 156,
    name: 'airport_transfer',
    visual_resource: 'transfer',
    description: 'Traslado do/para aeroporto',
    imagePath: transfer,
  },
  {
    amenity_id: 158,
    name: 'spa',
    visual_resource: 'spa',
    description: 'SPA',
    imagePath: spa,
  },
  {
    amenity_id: 160,
    name: 'no_smoking_floor',
    visual_resource: 'no_smoking',
    description: 'Andar exclusivo p/ não fumantes',
  },
  {
    amenity_id: 162,
    name: 'no_smoking_apartment',
    visual_resource: 'no_smoking',
    description: 'Apartamento exclusivo p/ não fumantes',
  },
  {
    amenity_id: 168,
    name: 'pet_access',
    visual_resource: 'pet_access',
    description: 'Permite pets (animais domésticos)',
    imagePath: petAccess,
  },
  {
    amenity_id: 50,
    name: 'antiallergic_apartment',
    visual_resource: 'antiallergic_apartment',
    description: 'Apartamento antialérgico',
  },
  {
    amenity_id: 56,
    name: 'lounge',
    visual_resource: 'lounge',
    description: 'Bar/Lounge',
    imagePath: barLouge,
  },
  {
    amenity_id: 60,
    name: 'coffee_shop',
    visual_resource: 'coffee_shop',
    description: 'Cafeteria',
    imagePath: coffeeShop,
  },
  {
    amenity_id: 66,
    name: 'express_checkout',
    visual_resource: 'express_checkout',
    description: 'Express Check-out',
    imagePath: checkout,
  },
  {
    amenity_id: 68,
    name: 'baggage',
    visual_resource: 'baggage',
    description: 'Guarda bagagem',
    imagePath: baggage,
  },
  {
    amenity_id: 70,
    name: 'rental_agency',
    visual_resource: 'rental_agency',
    description: 'Locadora de veÍculos',
    imagePath: rentalAgency,
  },
  {
    amenity_id: 72,
    name: 'convenience_store',
    visual_resource: 'convenience_store',
    description: 'Loja de conveniência',
    imagePath: convenienceStore,
  },
  {
    amenity_id: 74,
    name: 'valet_parking',
    visual_resource: 'valet_parking',
    description: 'Manobrista',
    imagePath: valetParking,
  },
  {
    amenity_id: 76,
    name: 'dry_sauna',
    visual_resource: 'dry_sauna',
    description: 'Sauna seca',
    imagePath: drySauna,
  },
  {
    amenity_id: 78,
    name: 'steam_sauna',
    visual_resource: 'steam_sauna',
    description: 'Sauna a vapor',
    imagePath: steamSauna,
  },
  {
    amenity_id: 84,
    name: 'laundry',
    visual_resource: 'laundry',
    description: 'Serviço de lavanderia',
    imagePath: laundry,
  },
  {
    amenity_id: 86,
    name: 'dry_laundry',
    visual_resource: 'dry_laundry',
    description: 'Serviço de lavanderia - a seco',
    imagePath: dryLaundry,
  },
  {
    amenity_id: 88,
    name: 'flatiron',
    visual_resource: 'flatiron',
    description: 'Serviço de passar roupa',
    imagePath: flatiron,
  },
  {
    amenity_id: 90,
    name: 'room_service',
    visual_resource: 'room_service',
    description: 'Serviço de quarto',
    imagePath: roomService,
  },
  {
    amenity_id: 92,
    name: 'room_service_24',
    visual_resource: 'room_service_24',
    description: 'Serviço de quarto 24h',
    imagePath: roomService24,
  },
  {
    amenity_id: 170,
    name: 'tv',
    visual_resource: 'tv',
    description: 'TV a cabo',
  },
  {
    amenity_id: 176,
    name: 'room_air_conditioner',
    visual_resource: 'air_conditioner',
    description: 'Ar-condicionado',
    imagePath: air,
  },
  {
    amenity_id: 196,
    name: 'room_notebook_stand',
    visual_resource: 'notebook_stand',
    description: 'Bancada para notebook',
    imagePath: notebookStand,
  },
  {
    amenity_id: 198,
    name: 'room_kitchen',
    visual_resource: 'kitchen',
    description: 'Cozinha',
    imagePath: kitchen,
  },
  {
    amenity_id: 204,
    name: 'room_vault',
    visual_resource: 'vault',
    description: 'Cofre',
    imagePath: vault,
  },
  {
    amenity_id: 206,
    name: 'room_smoke_detector',
    visual_resource: 'smoke_detector',
    description: 'Detector de fumaça',
    imagePath: smokeDetector,
  },
  {
    amenity_id: 209,
    name: 'hairdryer',
    visual_resource: 'room_service',
    description: 'Secador de cabelos',
  },
  {
    amenity_id: 210,
    name: 'sprinkler',
    visual_resource: 'room_service',
    description: 'Borrifador',
  },
  {
    amenity_id: 211,
    name: 'ironwork',
    visual_resource: 'room_service',
    description: 'Ferro de passar',
  },
  {
    amenity_id: 212,
    name: 'tableware',
    visual_resource: 'restaurant_menu',
    description: 'Talheres e louça',
  },
  {
    amenity_id: 213,
    name: 'phone',
    visual_resource: 'phone',
    description: 'Telefone',
  },
  {
    amenity_id: 215,
    name: 'porch',
    visual_resource: 'view_day',
    description: 'Sacada',
  },
  {
    amenity_id: 216,
    name: 'porch_overlooking_sea',
    visual_resource: 'broken_image',
    description: 'Sacada com vista para o mar',
  },
  {
    amenity_id: 217,
    name: 'anti_noise_glass',
    visual_resource: 'hearing',
    description: 'Vidros anti-ruidos',
  },
  {
    amenity_id: 218,
    name: 'high_speed_internet_access',
    visual_resource: 'network_check',
    description: 'Internet alta velocidade',
  },
  {
    amenity_id: 219,
    name: 'libra',
    visual_resource: 'account_balance_wallet',
    description: 'Balança',
  },
  {
    amenity_id: 220,
    name: 'bathroom_with_bathtub',
    visual_resource: 'bathtub',
    description: 'Banheiro com banheira',
  },
  {
    amenity_id: 221,
    name: 'cd_player',
    visual_resource: 'album',
    description: 'CD player',
  },
  {
    amenity_id: 223,
    name: 'clime_air_conditioner',
    visual_resource: 'wbIridescent',
    description: 'Climatizador',
  },
  {
    amenity_id: 224,
    name: 'digital_safe',
    visual_resource: 'lock',
    description: 'Cofre digital',
  },
  {
    amenity_id: 225,
    name: 'eletronic_lock',
    visual_resource: 'screen_lock_rotation',
    description: 'Fechadura eletronica',
  },
  {
    amenity_id: 226,
    name: 'mini_bar',
    visual_resource: 'local_bar',
    description: 'Frigobar',
  },
  {
    amenity_id: 227,
    name: 'jacuzzi',
    visual_resource: 'hot_tub',
    description: 'Jacuzzi',
  },
  {
    amenity_id: 228,
    name: 'microwave',
    visual_resource: 'waves',
    description: 'Microondas',
  },
  {
    amenity_id: 229,
    name: 'anti_noise_wall',
    visual_resource: 'hearing',
    description: 'Parede anti-ruidos',
  },
  {
    amenity_id: 231,
    name: 'stay_room_service',
    visual_resource: 'room_service',
    description: 'Room service',
  },
  {
    amenity_id: 232,
    name: 'robe',
    visual_resource: 'broken_image',
    description: 'Roupao',
  },
  {
    amenity_id: 233,
    name: 'computer_socket',
    visual_resource: 'power',
    description: 'Tomada para computador',
    imagePath: power,
  },
  {
    amenity_id: 234,
    name: 'voice_mail',
    visual_resource: 'record_voice_over',
    description: 'Correio de voz',
  },
  {
    amenity_id: 235,
    name: 'executive_internet_access',
    visual_resource: 'wifi_lock',
    description: 'Intenet executiva',
  },
  {
    amenity_id: 236,
    name: 'radio_watch',
    visual_resource: 'radio',
    description: 'Rario relogio',
  },
  {
    amenity_id: 237,
    name: 'full_kitchen',
    visual_resource: 'kitchen',
    description: 'Cozinha completa',
  },
  {
    amenity_id: 238,
    name: 'oven',
    visual_resource: 'whatshot',
    description: 'Forno',
  },
  {
    amenity_id: 239,
    name: 'fridge',
    visual_resource: 'kitchen',
    description: 'Geladeira',
  },
  {
    amenity_id: 240,
    name: 'dishwasher',
    visual_resource: 'repeat',
    description: 'Lava-louças',
  },
  {
    amenity_id: 243,
    name: 'kitchen_utensils',
    visual_resource: 'kitchen',
    description: 'Utensilios de cozinha',
  },
  {
    amenity_id: 242,
    name: 'dries_washing_machine',
    visual_resource: 'local_laundry_service',
    description: 'Maquina de lavar e secar',
  },
  {
    amenity_id: 241,
    name: 'washing_machine',
    visual_resource: 'local_laundry_service',
    description: 'Maquina de lavar',
  },
  {
    amenity_id: 244,
    name: 'housekeeping_service',
    visual_resource: 'clear_all',
    description: 'Serviço de limpeza',
  },
  {
    amenity_id: 245,
    name: 'tabacco_shop',
    visual_resource: 'smoking_rooms',
    description: 'Tabacaria',
  },
  {
    amenity_id: 246,
    name: 'vita_club',
    visual_resource: 'people_alt',
    description: 'Vita club',
  },
  {
    amenity_id: 247,
    name: 'rest_room',
    visual_resource: 'airline_seat_individual_suite',
    description: 'Sala de descanço',
  },
  {
    amenity_id: 248,
    name: 'security',
    visual_resource: 'security',
    description: 'Segurança',
  },
  {
    amenity_id: 249,
    name: 'mail_service',
    visual_resource: 'mail_outline',
    description: 'Serviço de correio',
  },
  {
    amenity_id: 250,
    name: 'beach_service',
    visual_resource: 'beach_access',
    description: 'Serviço de praia',
  },
  {
    amenity_id: 252,
    name: 'taxi_service',
    visual_resource: 'local_taxi',
    description: 'Serviço de taxi',
  },
  {
    amenity_id: 253,
    name: 'public_phone',
    visual_resource: 'phone_enabled',
    description: 'Telefone publico',
  },
  {
    amenity_id: 254,
    name: 'health_unit',
    visual_resource: 'local_hospital',
    description: 'Unidade de saude',
  },
  {
    amenity_id: 256,
    name: 'handicapped_room',
    visual_resource: 'accessible',
    description: 'Quarto para deficiente',
  },
  {
    amenity_id: 258,
    name: 'alarm_clock_call',
    visual_resource: 'access_alarms',
    description: 'Chamada despertador',
  },
  {
    amenity_id: 259,
    name: 'currency_exchange',
    visual_resource: 'local_atm',
    description: 'Casa de cambio',
  },
  {
    amenity_id: 260,
    name: 'event_hall',
    visual_resource: 'event_seat',
    description: 'Casa de eventos',
  },
  {
    amenity_id: 261,
    name: 'air_early_checkin',
    visual_resource: 'airline_seat_recline_extra',
    description: 'Check-in antecipado (aereo)',
  },
  {
    amenity_id: 262,
    name: 'barbecue_grill',
    visual_resource: 'outdoor_grill',
    description: 'Churrasqueira',
  },
  {
    amenity_id: 263,
    name: 'vault_at_reception',
    visual_resource: 'lock_open',
    description: 'Cofre na recepção',
  },
  {
    amenity_id: 264,
    name: 'cyber_coffee',
    visual_resource: 'local_cafe',
    description: 'Cyber cafe',
  },
  {
    amenity_id: 265,
    name: 'flower_shop',
    visual_resource: 'local_florist',
    description: 'Floricultura',
  },
  {
    amenity_id: 266,
    name: 'messenger',
    visual_resource: 'messenger',
    description: 'Mensageiro',
  },
  {
    amenity_id: 267,
    name: 'outdoor_training',
    visual_resource: 'fitness_center',
    description: 'Outdoor traininig',
  },
  {
    amenity_id: 269,
    name: 'hotel_home_theater',
    visual_resource: 'surround_sound',
    description: 'Home theater',
  },
  {
    amenity_id: 270,
    name: 'travel_agency',
    visual_resource: 'travel_agency',
    description: 'Agencia de viagem',
  },
  {
    amenity_id: 271,
    name: 'nightclub',
    visual_resource: 'nightclub',
    description: 'Night club',
  },
  {
    amenity_id: 272,
    name: 'gym_agreement',
    visual_resource: 'gym_agreement',
    description: 'Convenio com academia',
  },
  {
    amenity_id: 273,
    name: 'video_center',
    visual_resource: 'video_center',
    description: 'Central de video',
  },
  {
    amenity_id: 274,
    name: 'reception_appointment',
    visual_resource: 'reception_appointment',
    description: 'Recepção com hora marcada',
  },
  {
    amenity_id: 275,
    name: 'condominium',
    visual_resource: 'condominium',
    description: 'Condominio',
  },
  {
    amenity_id: 276,
    name: 'phone_calls',
    visual_resource: 'phone_calls',
    description: 'Ligações telefônicas',
  },
];

export function getAmenityValue(name: string): IAmenity | null {
  const amenity = amenities.find((amenity) => amenity.name === name);

  return amenity || null
}
